ADMIN_HTML = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>不求人 · 内部卷宗</title><style>
*{box-sizing:border-box}body{margin:0;background:#11100e;color:#e9e3d8;font:14px/1.65 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.top{position:sticky;top:0;background:#171512;border-bottom:1px solid #36312a;padding:14px 20px;display:flex;justify-content:space-between;align-items:center}.top b{letter-spacing:.16em}.note{color:#928a7d;font-size:12px}.grid{display:grid;grid-template-columns:390px 1fr;min-height:calc(100vh - 58px)}.left{border-right:1px solid #302c26;padding:16px;overflow:auto}.right{padding:20px;overflow:auto}.user{padding:12px;border:1px solid #322e28;margin:0 0 9px;cursor:pointer;background:#181613}.user:hover,.user.active{border-color:#7e6950;background:#211e19}.name{font-size:15px;color:#fff}.meta{font-size:11px;color:#978e80;margin-top:5px}.badge{display:inline-block;border:1px solid #51493e;padding:1px 5px;margin-right:5px}pre{white-space:pre-wrap;word-break:break-word;margin:0;color:#d8d1c5;background:#161411;border:1px solid #312d27;padding:18px;min-height:280px}.search{width:100%;background:#12110f;color:#eee;border:1px solid #3c372f;padding:9px 10px;margin-bottom:12px}button{background:#28231d;color:#eee;border:1px solid #554b3f;padding:7px 10px;cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}.left{border-right:0;border-bottom:1px solid #302c26;max-height:45vh}}</style></head>
<body><div class="top"><div><b>/WOTAMADE</b> <span class="note">内部卷宗 · Security fields redacted</span></div><button onclick="loadUsers()">刷新</button></div><div class="grid"><aside class="left"><input id="q" class="search" placeholder="筛选用户名 / 称呼" oninput="render()"><div id="users"></div></aside><main class="right"><pre id="dump">选择一个账号查看档案、命盘缓存索引、会话、消息、附件元数据与审计记录。\n\n密码哈希、会话令牌、CSRF、平台 Secret 不在此页返回。</pre></main></div><script>
let all=[],active=null;const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function req(url){const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function loadUsers(){try{const d=await req('/api/admin/users');all=d.items||[];render()}catch(e){document.querySelector('#dump').textContent='读取失败：'+e.message}}
function render(){const q=document.querySelector('#q').value.trim().toLowerCase();const rows=all.filter(x=>!q||String(x.username).toLowerCase().includes(q)||String(x.display_name||'').toLowerCase().includes(q));document.querySelector('#users').innerHTML=rows.map(x=>'<div class="user '+(active===x.id?'active':'')+'" data-id="'+x.id+'"><div class="name">'+esc(x.username)+' '+(x.display_name?'· '+esc(x.display_name):'')+'</div><div class="meta"><span class="badge">#'+x.id+'</span><span class="badge">'+esc(x.role)+'</span> 对话 '+x.conversation_count+' · 消息 '+x.message_count+' · 附件 '+x.attachment_count+'<br>最近登录 '+esc(x.last_login_at||'—')+'</div></div>').join('');document.querySelectorAll('.user').forEach(el=>el.onclick=()=>openUser(Number(el.dataset.id)))}
async function openUser(id){active=id;render();document.querySelector('#dump').textContent='读取中…';try{const d=await req('/api/admin/user?id='+id);document.querySelector('#dump').textContent=JSON.stringify(d,null,2)}catch(e){document.querySelector('#dump').textContent='读取失败：'+e.message}}
loadUsers();</script></body></html>'''
