APP_HTML = r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<meta name="theme-color" content="#15130f" />
<title>不求人 · 命理推演</title>
<style>
:root{--ink:#1b1915;--paper:#f3efe5;--paper2:#e9e2d2;--line:#cfc5b2;--muted:#756e62;--seal:#8f2f24;--gold:#907446;--shadow:0 18px 60px rgba(37,31,22,.12)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:"Noto Serif SC","Songti SC","SimSun",serif;background:#ddd6c7;color:var(--ink)}button,input,select,textarea{font:inherit}button{cursor:pointer}.hidden{display:none!important}
body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.15;background-image:radial-gradient(#352f24 .45px,transparent .45px);background-size:5px 5px}.shell{min-height:100vh;display:flex;flex-direction:column}.topbar{height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 24px;background:#15130f;color:#eee8dc;border-bottom:1px solid #322e27;position:sticky;top:0;z-index:20}.brand{display:flex;align-items:center;gap:12px}.seal{width:36px;height:36px;border:1px solid #c96458;color:#e78f84;display:grid;place-items:center;font-weight:800;letter-spacing:2px;line-height:1;font-size:14px}.brand h1{font-size:18px;letter-spacing:.18em;margin:0}.brand small{color:#958d80;margin-left:4px}.top-actions{display:flex;gap:8px}.ghost,.primary,.danger{border:1px solid #b5aa97;background:transparent;padding:9px 14px;border-radius:2px}.topbar .ghost{color:#d8d0c4;border-color:#49443b}.primary{background:var(--ink);border-color:var(--ink);color:#fff}.danger{color:#88291f;border-color:#b87870}
.layout{flex:1;display:grid;grid-template-columns:270px minmax(0,1fr);min-height:0}.sidebar{background:#e8e1d3;border-right:1px solid var(--line);padding:18px;display:flex;flex-direction:column;gap:14px}.newchat{width:100%;padding:11px;border:1px solid #6d6457;background:#f6f1e7}.case-list{display:flex;flex-direction:column;gap:6px;overflow:auto}.case{padding:11px 10px;border-left:2px solid transparent;color:#4d483f;background:transparent;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer}.case:hover,.case.active{background:#f5f0e5;border-left-color:var(--seal)}.profile-mini{margin-top:auto;border-top:1px solid var(--line);padding-top:13px;font-size:13px;color:var(--muted)}.profile-mini strong{display:block;color:var(--ink);font-size:15px;margin-bottom:4px}.main{min-width:0;background:var(--paper);display:flex;flex-direction:column}.hero-empty{margin:auto;max-width:700px;padding:50px 30px;text-align:center}.hero-empty .mark{font-size:54px;color:#9d8b69;opacity:.55}.hero-empty h2{font-weight:500;letter-spacing:.12em}.hero-empty p{line-height:1.9;color:var(--muted)}
.messages{flex:1;overflow:auto;padding:28px max(22px,calc((100% - 940px)/2));scroll-behavior:smooth}.msg{margin:0 0 28px;display:grid;grid-template-columns:46px minmax(0,1fr);gap:14px}.avatar{width:38px;height:38px;border:1px solid #ada28f;display:grid;place-items:center;font-size:12px;color:#625b4f}.msg.assistant .avatar{background:#27231d;color:#efe7d8;border-color:#27231d}.bubble{min-width:0}.meta{font-size:12px;color:#8b8376;margin-bottom:7px;display:flex;align-items:center;gap:8px}.model-pill{display:none!important}.content{line-height:1.95;font-family:"Noto Serif SC","Songti SC",serif;font-size:15px;overflow-wrap:anywhere}.msg.user .content{white-space:pre-wrap;background:#e9e1d2;border:1px solid #d7cbb7;padding:13px 15px}.msg.assistant .content{white-space:normal}.msg.assistant.streaming .content:after{content:"";display:inline-block;width:7px;height:1.15em;margin-left:3px;vertical-align:-.2em;background:#92734d;animation:blink .9s steps(1) infinite}@keyframes blink{50%{opacity:0}}
.reasoning{margin:3px 0 16px;border:1px solid #d0c4af;background:#ebe3d5}.reasoning summary{list-style:none;cursor:pointer;padding:9px 12px;color:#7b6c58;font-size:12px;letter-spacing:.08em;display:flex;align-items:center;gap:8px}.reasoning summary::-webkit-details-marker{display:none}.reasoning summary:before{content:"◇";font-size:11px;color:#8f2f24}.reasoning[open] summary{border-bottom:1px solid #d8ccba}.reasoning-body{max-height:260px;overflow:auto;padding:12px 14px;white-space:pre-wrap;font-family:"Songti SC","Noto Serif SC",serif;font-size:12px;line-height:1.85;color:#746b5f;background:rgba(255,255,255,.2)}.reasoning.live .reasoning-body:after{content:" ▌";animation:blink .9s steps(1) infinite;color:#8f2f24}.answer-label{font-size:11px;color:#9a8b77;letter-spacing:.14em;margin:0 0 8px}
/* Markdown */
.markdown>*:first-child{margin-top:0}.markdown>*:last-child{margin-bottom:0}.markdown h1,.markdown h2,.markdown h3,.markdown h4{font-weight:600;line-height:1.45;color:#211d18;margin:1.55em 0 .65em}.markdown h1{font-size:1.55em;border-bottom:1px solid #cfc1ab;padding-bottom:.35em}.markdown h2{font-size:1.32em;border-left:3px solid #8f2f24;padding-left:.65em}.markdown h3{font-size:1.14em}.markdown h4{font-size:1.02em;color:#5f5548}.markdown p{margin:.7em 0 1.05em}.markdown strong{color:#5f261f;font-weight:700}.markdown em{color:#655b4e}.markdown ul,.markdown ol{padding-left:1.55em;margin:.65em 0 1.05em}.markdown li{margin:.35em 0}.markdown blockquote{margin:1em 0;padding:.65em 1em;border-left:3px solid #a68d65;background:#ece4d6;color:#5f5548}.markdown code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:.9em;background:#e7dfd1;padding:.12em .35em;border-radius:2px}.markdown pre{overflow:auto;background:#242019;color:#eee6d8;padding:14px 16px;border-radius:2px;line-height:1.65}.markdown pre code{background:none;padding:0;color:inherit}.markdown a{color:#7d352c;text-decoration-color:#b58c83}.markdown hr{border:0;border-top:1px solid #cfc2af;margin:1.6em 0}.md-table-wrap{overflow:auto;margin:1em 0}.markdown table{border-collapse:collapse;width:100%;font-size:13px}.markdown th,.markdown td{border:1px solid #cfc2af;padding:8px 10px;text-align:left;vertical-align:top}.markdown th{background:#e8dfd0;color:#4e4539}.markdown tr:nth-child(even) td{background:rgba(230,221,206,.35)}
.attachments-inline{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px}.attachment-chip{font-size:12px;border:1px solid #c7bca9;background:#eee7db;padding:6px 8px;color:#665e52}.composer-wrap{border-top:1px solid var(--line);background:#ece5d8;padding:13px max(18px,calc((100% - 940px)/2)) 18px}.attachment-tray{display:flex;gap:8px;overflow:auto;margin-bottom:8px}.preview{position:relative;min-width:92px;max-width:150px;height:70px;border:1px solid #b8ad99;background:#ddd5c6;display:flex;align-items:center;justify-content:center;overflow:hidden;font-size:11px;color:#554d42}.preview img{width:100%;height:100%;object-fit:cover}.preview button{position:absolute;right:3px;top:3px;border:0;background:rgba(0,0,0,.65);color:#fff;width:20px;height:20px}.composer{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:end;gap:8px;border:1px solid #aaa08f;background:#f8f3e9;padding:8px}.composer textarea{border:0;outline:0;background:transparent;resize:none;min-height:44px;max-height:180px;padding:8px;line-height:1.6}.attach-btn{width:42px;height:42px;border:0;background:transparent;font-size:20px}.send{height:42px;min-width:72px;border:0;background:#211e19;color:#fff;padding:0 16px}.hint{font-size:11px;color:#8a8275;margin:6px 2px 0}.footer{font-size:10px;color:#81796d;text-align:center;padding:10px 18px 16px;line-height:1.8;border-top:1px solid rgba(176,164,145,.4);background:var(--paper)}
.auth-wrap{min-height:100vh;display:grid;place-items:center;padding:28px;background:#17140f}.auth-card{width:min(440px,100%);background:#f2ede2;padding:34px;box-shadow:0 25px 80px rgba(0,0,0,.28);border:1px solid #756b5b}.auth-title{text-align:center;margin-bottom:28px}.auth-title .seal{margin:0 auto 12px;width:48px;height:48px;color:#8f2f24;border-color:#8f2f24}.auth-title h1{font-weight:500;letter-spacing:.24em;margin:8px 0}.tabs{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid #c7bdab;margin-bottom:20px}.tab{padding:10px;border:0;background:none;color:#797164}.tab.active{color:#1d1a16;border-bottom:2px solid #8f2f24}.field{margin:13px 0}.field label{display:block;font-size:12px;color:#70685c;margin-bottom:6px}.field input,.field select{width:100%;border:1px solid #b9ad99;background:#faf7f0;padding:11px;outline:none}.field input:focus,.field select:focus{border-color:#6b5c48}.auth-card .primary{width:100%;padding:12px;margin-top:8px}.error{color:#9b281f;font-size:13px;min-height:20px;margin-top:10px}.modal{position:fixed;inset:0;background:rgba(20,17,13,.62);z-index:50;display:grid;place-items:center;padding:20px}.panel{width:min(620px,100%);max-height:92vh;overflow:auto;background:#f3eee4;border:1px solid #6e6353;box-shadow:var(--shadow);padding:26px}.panel h2{font-weight:500;letter-spacing:.08em;margin:0 0 6px}.panel .sub{font-size:13px;color:var(--muted);line-height:1.7;margin-bottom:20px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid3{display:grid;grid-template-columns:1.3fr 1fr 1fr;gap:10px}.row{display:flex;gap:10px;align-items:center}.row.end{justify-content:flex-end;margin-top:20px}.check{display:flex;gap:8px;align-items:center;font-size:13px;color:#665e53}.profile-lock{border-left:3px solid var(--seal);background:#ece1cf;padding:12px 14px;margin-bottom:16px;font-size:13px;line-height:1.7}.busy:after{content:"";display:inline-block;width:12px;height:12px;margin-left:8px;border:1px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
@media(max-width:760px){.layout{grid-template-columns:1fr}.sidebar{display:none}.topbar{padding:0 14px}.brand small{display:none}.messages{padding:20px 14px}.composer-wrap{padding:10px}.grid2,.grid3{grid-template-columns:1fr}.panel{padding:20px}.footer{font-size:9px}.top-actions button:first-child{display:none}.msg{grid-template-columns:34px minmax(0,1fr);gap:9px}.avatar{width:30px;height:30px}}
</style>
</head>
<body>
<div id="auth" class="auth-wrap">
  <div class="auth-card">
    <div class="auth-title"><div class="seal">不求</div><h1>不求人</h1><div style="color:#746c60;font-size:12px">命理不是答案，是一套观察时间与人的旧方法。</div></div>
    <div class="tabs"><button id="loginTab" class="tab active">登录</button><button id="registerTab" class="tab">注册</button></div>
    <form id="authForm">
      <div class="field"><label>用户名</label><input id="username" autocomplete="username" maxlength="32" required /></div>
      <div class="field"><label>密码</label><input id="password" type="password" autocomplete="current-password" minlength="8" required /></div>
      <button id="authSubmit" class="primary" type="submit">进入</button><div id="authError" class="error"></div>
    </form>
  </div>
</div>

<div id="app" class="shell hidden">
  <header class="topbar"><div class="brand"><div class="seal">不求</div><h1>不求人</h1><small>命理推演案</small></div><div class="top-actions"><button class="ghost" id="profileBtn">命理档案</button><button class="ghost" id="passwordBtn">改密码</button><button class="ghost" id="logoutBtn">退出</button></div></header>
  <div class="layout">
    <aside class="sidebar"><button class="newchat" id="newChatBtn">＋ 新开一案</button><div class="case-list" id="caseList"></div><div class="profile-mini" id="profileMini"></div></aside>
    <main class="main">
      <div id="empty" class="hero-empty"><div class="mark">☰</div><h2>先看盘，再问事</h2><p>盘有骨，运有势。先看气从哪里来、往哪里去，再落到你眼下真正过不去的那道关。</p></div>
      <div id="messages" class="messages hidden"></div>
      <div class="composer-wrap"><div id="attachmentTray" class="attachment-tray"></div><div class="composer"><button id="attachBtn" class="attach-btn" title="添加图片或视频">＋</button><input id="fileInput" type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" class="hidden"/><textarea id="prompt" placeholder="说你现在真正想问的事……" rows="1"></textarea><button id="sendBtn" class="send">推演</button></div><div class="hint">支持多图与视频。推演时会先显“观盘心路”，再逐字落下正文；Markdown 标题、加粗、列表、表格会正常排版。</div></div>
    </main>
  </div>
  <footer class="footer">参考体系：《子平真诠》 · 《滴天髓》 · 《穷通宝鉴》 · 《渊海子平》 · 《三命通会》 · 《神峰通考》 · 《千里命稿》 · 《周易》 · 《梅花易数》　｜　古法各有门径，本站以可复核盘面为先，不伪造古籍原文与页码。</footer>
</div>

<div id="profileModal" class="modal hidden"><div class="panel"><h2>命理档案</h2><div class="sub">这是推演的底盘。只保存称呼、性别与出生信息；资料不完整时，对话会被锁定。</div><div id="profileLock" class="profile-lock hidden">先把以下资料补齐。时辰确实不知道就选“未知”，系统会保留时柱不确定性，不会瞎编一个时辰。</div><form id="profileForm"><div class="grid2"><div class="field"><label>称呼</label><input id="displayName" maxlength="30" required /></div><div class="field"><label>性别</label><select id="gender" required><option value="male">男</option><option value="female">女</option></select></div></div><div class="grid2"><div class="field"><label>历法</label><select id="calendarType"><option value="solar">公历</option><option value="lunar">农历</option></select></div><div class="field" id="leapBox"><label>农历闰月</label><label class="check"><input id="leapMonth" type="checkbox"/> 这是闰月</label></div></div><div class="grid3"><div class="field"><label>年</label><input id="birthYear" type="number" min="1850" max="2100" required /></div><div class="field"><label>月</label><input id="birthMonth" type="number" min="1" max="12" required /></div><div class="field"><label>日</label><input id="birthDay" type="number" min="1" max="31" required /></div></div><div class="field"><label>出生时辰</label><select id="birthHour"><option value="unknown">未知</option></select></div><div id="profileError" class="error"></div><div class="row end"><button type="button" class="ghost" id="profileCancel">取消</button><button class="primary" type="submit">保存并重新定盘</button></div></form></div></div>

<div id="passwordModal" class="modal hidden"><div class="panel" style="max-width:460px"><h2>修改密码</h2><form id="passwordForm"><div class="field"><label>当前密码</label><input id="oldPassword" type="password" required minlength="8" /></div><div class="field"><label>新密码</label><input id="newPassword" type="password" required minlength="8" /></div><div id="passwordError" class="error"></div><div class="row end"><button type="button" class="ghost" id="passwordCancel">取消</button><button class="primary" type="submit">确认修改</button></div></form></div></div>

<script>
const $=s=>document.querySelector(s);const state={mode:'login',me:null,csrf:'',profile:null,conversations:[],conversationId:null,pending:[],busy:false};
for(let h=0;h<24;h++){const o=document.createElement('option');o.value=h;o.textContent=String(h).padStart(2,'0')+':00';$('#birthHour').appendChild(o)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function inlineMd(s){
  let x=s;
  x=x.replace(/`([^`]+)`/g,'<code>$1</code>');
  x=x.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
  x=x.replace(/__([^_]+)__/g,'<strong>$1</strong>');
  x=x.replace(/(^|[^*])\*([^*\n]+)\*/g,'$1<em>$2</em>');
  x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
  return x;
}
function isTableSep(line){return /^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$/.test(line)}
function tableCells(line){return line.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(x=>inlineMd(x.trim()))}
function renderMarkdown(src){
  const lines=esc(src||'').replace(/\r\n?/g,'\n').split('\n');let out=[],i=0,inCode=false,code=[];
  const closeLists=()=>{while(out.length&&out[out.length-1]==='__LIST_OPEN__')out.pop()};
  while(i<lines.length){let line=lines[i];
    if(/^```/.test(line.trim())){if(!inCode){inCode=true;code=[]}else{out.push('<pre><code>'+code.join('\n')+'</code></pre>');inCode=false}i++;continue}
    if(inCode){code.push(line);i++;continue}
    if(line.includes('|')&&i+1<lines.length&&isTableSep(lines[i+1])){const heads=tableCells(line);i+=2;const rows=[];while(i<lines.length&&lines[i].includes('|')&&lines[i].trim()){rows.push(tableCells(lines[i]));i++}let t='<div class="md-table-wrap"><table><thead><tr>'+heads.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>';for(const r of rows)t+='<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>';t+='</tbody></table></div>';out.push(t);continue}
    const hm=line.match(/^(#{1,4})\s+(.+)$/);if(hm){out.push('<h'+hm[1].length+'>'+inlineMd(hm[2])+'</h'+hm[1].length+'>');i++;continue}
    if(/^\s*---+\s*$/.test(line)){out.push('<hr>');i++;continue}
    if(/^\s*>\s?/.test(line)){const qs=[];while(i<lines.length&&/^\s*>\s?/.test(lines[i])){qs.push(lines[i].replace(/^\s*>\s?/,''));i++}out.push('<blockquote>'+inlineMd(qs.join('<br>'))+'</blockquote>');continue}
    if(/^\s*[-*+]\s+/.test(line)){const xs=[];while(i<lines.length&&/^\s*[-*+]\s+/.test(lines[i])){xs.push(lines[i].replace(/^\s*[-*+]\s+/,''));i++}out.push('<ul>'+xs.map(x=>'<li>'+inlineMd(x)+'</li>').join('')+'</ul>');continue}
    if(/^\s*\d+[.)]\s+/.test(line)){const xs=[];while(i<lines.length&&/^\s*\d+[.)]\s+/.test(lines[i])){xs.push(lines[i].replace(/^\s*\d+[.)]\s+/,''));i++}out.push('<ol>'+xs.map(x=>'<li>'+inlineMd(x)+'</li>').join('')+'</ol>');continue}
    if(!line.trim()){i++;continue}
    const ps=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,4})\s+/.test(lines[i])&&!/^```/.test(lines[i].trim())&&!/^\s*>\s?/.test(lines[i])&&!/^\s*[-*+]\s+/.test(lines[i])&&!/^\s*\d+[.)]\s+/.test(lines[i])&&!(lines[i].includes('|')&&i+1<lines.length&&isTableSep(lines[i+1]))){ps.push(lines[i]);i++}out.push('<p>'+inlineMd(ps.join('<br>'))+'</p>');
  }
  if(inCode)out.push('<pre><code>'+code.join('\n')+'</code></pre>');return out.join('');
}
async function api(path,opt={}){const headers=new Headers(opt.headers||{});if(opt.json!==undefined){headers.set('Content-Type','application/json');opt.body=JSON.stringify(opt.json)}if(state.csrf&&['POST','PUT','PATCH','DELETE'].includes((opt.method||'GET').toUpperCase()))headers.set('X-CSRF-Token',state.csrf);const r=await fetch(path,{credentials:'same-origin',...opt,headers});let d=null;const ct=r.headers.get('content-type')||'';try{d=ct.includes('json')?await r.json():await r.text()}catch{}if(!r.ok){const e=new Error((d&&d.error)||d||('HTTP '+r.status));e.status=r.status;throw e}return d}
function setAuthMode(mode){state.mode=mode;$('#loginTab').classList.toggle('active',mode==='login');$('#registerTab').classList.toggle('active',mode==='register');$('#authSubmit').textContent=mode==='login'?'进入':'建立账号';$('#password').autocomplete=mode==='login'?'current-password':'new-password';$('#authError').textContent=''}
$('#loginTab').onclick=()=>setAuthMode('login');$('#registerTab').onclick=()=>setAuthMode('register');
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';try{const d=await api('/api/'+state.mode,{method:'POST',json:{username:$('#username').value,password:$('#password').value}});state.csrf=d.csrf;await loadMe()}catch(err){$('#authError').textContent=err.message}}
async function loadMe(){try{const d=await api('/api/me');state.me=d.user;state.csrf=d.csrf||state.csrf;state.profile=d.profile;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');renderProfileMini();await loadConversations();if(!state.profile)openProfile(true)}catch(e){if(e.status===401){$('#auth').classList.remove('hidden');$('#app').classList.add('hidden')}else throw e}}
function renderProfileMini(){if(!state.profile){$('#profileMini').innerHTML='<strong>资料未定</strong>先完成命理档案';return}const p=state.profile;const hour=p.birth_hour_unknown?'时辰未知':String(p.birth_hour).padStart(2,'0')+'时';$('#profileMini').innerHTML='<strong>'+esc(p.display_name)+'</strong>'+(p.gender==='male'?'男':'女')+' · '+(p.calendar_type==='solar'?'公历':'农历')+' '+p.birth_year+'-'+p.birth_month+'-'+p.birth_day+' · '+hour}
async function loadConversations(){const d=await api('/api/conversations');state.conversations=d.items||[];renderCases()}
function renderCases(){$('#caseList').innerHTML=state.conversations.map(c=>'<div class="case '+(c.id===state.conversationId?'active':'')+'" data-id="'+c.id+'">'+esc(c.title)+'</div>').join('');document.querySelectorAll('.case').forEach(x=>x.onclick=()=>openConversation(Number(x.dataset.id)))}
async function createConversation(){const d=await api('/api/conversations',{method:'POST',json:{}});state.conversationId=d.id;await loadConversations();showMessages([]);return d.id}
$('#newChatBtn').onclick=async()=>{await createConversation()};
async function openConversation(id){state.conversationId=id;const d=await api('/api/conversation?id='+encodeURIComponent(id));showMessages(d.messages||[]);renderCases()}
function showMessages(items){$('#empty').classList.add('hidden');$('#messages').classList.remove('hidden');$('#messages').innerHTML='';items.forEach(addMessage);scrollBottom()}
function createAssistantView(m={}){const box=document.createElement('div');box.className='msg assistant'+(m.live?' streaming':'');box.innerHTML='<div class="avatar">理</div><div class="bubble"><div class="meta"><span>不求人</span><span class="model-pill '+(m.model?'':'hidden')+'"></span></div><details class="reasoning '+(m.live?'live':'')+' '+(m.reasoning||m.live?'':'hidden')+'"><summary>'+(m.live?'观盘心路 · 正在推演':'观盘心路 · 已收束')+'</summary><div class="reasoning-body"></div></details><div class="answer-label">断 · 语</div><div class="content markdown"></div></div>';const v={box,reasoning:box.querySelector('.reasoning'),reasoningBody:box.querySelector('.reasoning-body'),summary:box.querySelector('.reasoning summary'),content:box.querySelector('.content'),model:box.querySelector('.model-pill'),reasoningText:m.reasoning||'',contentText:m.content||''};if(m.live)v.reasoning.open=true;if(v.reasoningText)v.reasoningBody.textContent=v.reasoningText;if(v.contentText)v.content.innerHTML=renderMarkdown(v.contentText);if(m.model){v.model.textContent=m.model+' · thinking';v.model.classList.remove('hidden')}$('#messages').appendChild(box);scrollBottom();return v}
function addMessage(m){if(m.role==='assistant'){return createAssistantView({content:m.content,reasoning:m.reasoning,model:m.model,live:false})}const box=document.createElement('div');box.className='msg user';box.innerHTML='<div class="avatar">问</div><div class="bubble"><div class="meta">你</div><div class="content">'+esc(m.content)+'</div></div>';$('#messages').appendChild(box);scrollBottom();return box}
function scrollBottom(){requestAnimationFrame(()=>{$('#messages').scrollTop=$('#messages').scrollHeight})}
function openProfile(required=false){const p=state.profile||{};$('#profileLock').classList.toggle('hidden',!required);$('#displayName').value=p.display_name||'';$('#gender').value=p.gender||'male';$('#calendarType').value=p.calendar_type||'solar';$('#birthYear').value=p.birth_year||'';$('#birthMonth').value=p.birth_month||'';$('#birthDay').value=p.birth_day||'';$('#birthHour').value=p.birth_hour_unknown||p.birth_hour==null?'unknown':String(p.birth_hour);$('#leapMonth').checked=!!p.leap_month;$('#profileModal').classList.remove('hidden');syncCalendar();$('#profileCancel').classList.toggle('hidden',required)}
function syncCalendar(){$('#leapBox').style.opacity=$('#calendarType').value==='lunar'?'1':'.35';$('#leapMonth').disabled=$('#calendarType').value!=='lunar'}
$('#calendarType').onchange=syncCalendar;$('#profileBtn').onclick=()=>openProfile(false);$('#profileCancel').onclick=()=>$('#profileModal').classList.add('hidden');
$('#profileForm').onsubmit=async e=>{e.preventDefault();$('#profileError').textContent='';const hv=$('#birthHour').value;const p={display_name:$('#displayName').value.trim(),gender:$('#gender').value,calendar_type:$('#calendarType').value,birth_year:Number($('#birthYear').value),birth_month:Number($('#birthMonth').value),birth_day:Number($('#birthDay').value),birth_hour:hv==='unknown'?null:Number(hv),birth_hour_unknown:hv==='unknown',leap_month:$('#calendarType').value==='lunar'&&$('#leapMonth').checked};try{const d=await api('/api/profile',{method:'PUT',json:p});state.profile=d.profile;renderProfileMini();$('#profileModal').classList.add('hidden')}catch(err){$('#profileError').textContent=err.message}}
$('#passwordBtn').onclick=()=>$('#passwordModal').classList.remove('hidden');$('#passwordCancel').onclick=()=>$('#passwordModal').classList.add('hidden');
$('#passwordForm').onsubmit=async e=>{e.preventDefault();$('#passwordError').textContent='';try{await api('/api/change-password',{method:'POST',json:{old_password:$('#oldPassword').value,new_password:$('#newPassword').value}});alert('密码已修改，请重新登录。');location.reload()}catch(err){$('#passwordError').textContent=err.message}}
$('#logoutBtn').onclick=async()=>{try{await api('/api/logout',{method:'POST',json:{}})}finally{location.reload()}};
$('#attachBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{for(const f of [...e.target.files]){if(state.pending.length>=8)break;const kind=f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':'other';const limit=kind==='image'?10*1024*1024:50*1024*1024;if(!['image','video'].includes(kind)){alert('当前仅接收图片与视频');continue}if(f.size>limit){alert(f.name+' 超过大小限制');continue}state.pending.push({file:f,kind,url:URL.createObjectURL(f),uploaded:null})}e.target.value='';renderPending()}
function renderPending(){$('#attachmentTray').innerHTML='';state.pending.forEach((x,i)=>{const d=document.createElement('div');d.className='preview';d.innerHTML=x.kind==='image'?'<img src="'+x.url+'" alt=""/>':'<span>视频 · '+esc(x.file.name)+'</span>';const b=document.createElement('button');b.textContent='×';b.onclick=()=>{URL.revokeObjectURL(x.url);state.pending.splice(i,1);renderPending()};d.appendChild(b);$('#attachmentTray').appendChild(d)})}
async function uploadPending(){if(!state.pending.length)return[];if(!state.conversationId)await createConversation();const ids=[];for(const item of state.pending){if(item.uploaded){ids.push(item.uploaded);continue}const q=new URLSearchParams({filename:item.file.name,mime:item.file.type||'application/octet-stream',size:String(item.file.size),conversation_id:String(state.conversationId)});const d=await api('/api/attachments?'+q.toString(),{method:'POST',headers:{'Content-Type':item.file.type||'application/octet-stream'},body:item.file});item.uploaded=d.id;ids.push(d.id)}return ids}
function clearPending(){state.pending.forEach(x=>URL.revokeObjectURL(x.url));state.pending=[];renderPending()}
async function streamChat(payload,view){const headers=new Headers({'Content-Type':'application/json','X-CSRF-Token':state.csrf});const r=await fetch('/api/chat',{method:'POST',credentials:'same-origin',headers,body:JSON.stringify({...payload,stream:true})});if(!r.ok){let d;try{d=await r.json()}catch{d={error:await r.text()}}throw new Error((d&&d.error)||('HTTP '+r.status))}if(!r.body)throw new Error('浏览器不支持流式响应');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',doneEvent=null;const consume=line=>{if(!line.trim())return;let ev;try{ev=JSON.parse(line)}catch{return}if(ev.type==='reasoning'){view.reasoning.classList.remove('hidden');view.reasoning.classList.add('live');view.reasoning.open=true;view.reasoningText+=ev.delta||'';view.reasoningBody.textContent=view.reasoningText;view.reasoningBody.scrollTop=view.reasoningBody.scrollHeight}else if(ev.type==='content'){view.contentText+=ev.delta||'';view.content.innerHTML=renderMarkdown(view.contentText)}else if(ev.type==='done'){doneEvent=ev;view.box.classList.remove('streaming');view.reasoning.classList.remove('live');view.summary.textContent='观盘心路 · 已收束';if(ev.model){view.model.textContent=ev.model+' · thinking';view.model.classList.remove('hidden')}if(ev.message){if(ev.message.reasoning){view.reasoningText=ev.message.reasoning;view.reasoningBody.textContent=view.reasoningText}if(ev.message.content){view.contentText=ev.message.content;view.content.innerHTML=renderMarkdown(view.contentText)}}}else if(ev.type==='error'){throw new Error(ev.error||'推演中断')}scrollBottom()};while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines)consume(line)}buffer+=decoder.decode();if(buffer.trim())consume(buffer);if(!doneEvent)throw new Error('流式推演未正常收束');return doneEvent}
$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#sendBtn').onclick=send;
async function send(){if(state.busy)return;if(!state.profile){openProfile(true);return}const text=$('#prompt').value.trim();if(!text&&!state.pending.length)return;state.busy=true;$('#sendBtn').classList.add('busy');$('#sendBtn').textContent='观盘中';let view=null;try{if(!state.conversationId)await createConversation();const attachment_ids=await uploadPending();addMessage({role:'user',content:text||'[附件]'});$('#prompt').value='';view=createAssistantView({live:true});await streamChat({conversation_id:state.conversationId,text,attachment_ids},view);clearPending();await loadConversations()}catch(err){if(!view)view=createAssistantView({live:false});view.box.classList.remove('streaming');view.reasoning.classList.remove('live');view.contentText='**本轮推演未完成。**\n\n'+String(err.message||err);view.content.innerHTML=renderMarkdown(view.contentText);view.summary.textContent='观盘心路 · 中断';clearPending()}finally{state.busy=false;$('#sendBtn').classList.remove('busy');$('#sendBtn').textContent='推演'}}
window.addEventListener('load',()=>loadMe());
</script>
</body></html>'''